services:
  db:
    image: postgres
    ports:
      - "${DB__PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER} -d $${PGDATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - ./backend/.env
    environment:
      - DB__HOSTNAME=db
      - REDIS__HOST=redis
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge